// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZTlYNeMjP2C440_Hcx5YVX0owVatluY',
    appId: '1:337011646532:web:352f91a8e11d8112079c11',
    messagingSenderId: '337011646532',
    projectId: 'ftwitter-355bc',
    authDomain: 'ftwitter-355bc.firebaseapp.com',
    storageBucket: 'ftwitter-355bc.appspot.com',
    measurementId: 'G-MKWDT53TEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BFs1g-NVotO0fDaRe5iwP15hgl3eeqs',
    appId: '1:337011646532:android:317f1579b498adce079c11',
    messagingSenderId: '337011646532',
    projectId: 'ftwitter-355bc',
    storageBucket: 'ftwitter-355bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UAo8OvK-FoVelgdNB5Vi89zIp8C7FFk',
    appId: '1:337011646532:ios:2b9d2d2b24c0f12f079c11',
    messagingSenderId: '337011646532',
    projectId: 'ftwitter-355bc',
    storageBucket: 'ftwitter-355bc.appspot.com',
    iosBundleId: 'com.example.ftwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6UAo8OvK-FoVelgdNB5Vi89zIp8C7FFk',
    appId: '1:337011646532:ios:11cae3009d0143c7079c11',
    messagingSenderId: '337011646532',
    projectId: 'ftwitter-355bc',
    storageBucket: 'ftwitter-355bc.appspot.com',
    iosBundleId: 'com.example.ftwitter.RunnerTests',
  );
}
